### ISSUE TITLE
Exception while start on node 4.1.1

### ISSUE THREAD

**Issue by Scorpibear** [workshopper/scope-chains-closures#15]
$ scope-chains-closures
...\npm\node_modules\scope-chains-closures\node_modules\adventure\lib\menu.js:51
    process.stdin.setRawMode(true);
                  ^

TypeError: process.stdin.setRawMode is not a function
    at module.exports (...\npm\node_modules\scope-chains-closures\node_modules\adventure\lib\menu.js:51:19)
    at Shop.showMenu (...\npm\node_modules\scope-chains-closures\node_modules\adventure\index.js:267:16)
    at Shop.execute (...\npm\node_modules\scope-chains-closures\node_modules\adventure\index.js:131:14)
    at Object.<anonymous> (...\npm\node_modules\scope-chains-closures\runner.js:26:6)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)

**Comment by martinheidegger** [comment]
Operating system and Terminal system please.

**Comment by ahstro** [comment]
Wouldn't `...\npm\node_modules\scope-chains-closures\node_modules\adventure\lib\menu.js:51` indicate that this is an error with the adventure module, not scope-chains-closures itself?
Also, I'm on v4.1.1 and am not experiencing any issues. Have you tried removing and reinstalling scope-chains-closures since the update? This solved issues with other modules when I moved to v4.0.0.

**Comment by Scorpibear** [comment]
npm rm scope-chains-closures
and
npm install -g scope-chains-closures
didn't help.
OS: windows 10
Terminal: MINGW64

**Comment by jesstelford** [comment]
Anyone got a Win10 box to test on?

**Comment by ghost** [comment]
I just recently had the same issue. And I am running Windows 10.

**Comment by buoyad** [comment]
Why is this closed? I'm still having the same problem. Is there a solution?

**Comment by SomeoneWeird** [comment]
This issue isn't closed.

What OS/node version are you on? :)

**Comment by buoyad** [comment]
Oh my bad. Saw the closed tag above my comment. 

I'm on Windows 10 with Node v4.4.2. I get this error using ootb git bash on Windows 10, but not on my Windows 7 machine at work. If I use [ConEmu](https://conemu.github.io/) on Windows 10, however, the program runs fine.

**Comment by martinheidegger** [comment]
#27 should fix this issue.
