### ISSUE TITLE
Windows 7 : typeError: process.stdin.setRawMode is not a function

### ISSUE THREAD

**Issue by ajaysunarthi** [workshopper/scope-chains-closures#25]
When I try to install this  it gives this error. My node version is 4.1.2

$ sccjs
C:\Users\AJAY\AppData\Roaming\npm\node_modules\scope-chains-closures\node_modules\adventure\lib\menu.js:51
    process.stdin.setRawMode(true);
                  ^

TypeError: process.stdin.setRawMode is not a function
    at module.exports (C:\Users\AJAY\AppData\Roaming\npm\node_modules\scope-chains-closures\node_modules\adventure\lib\menu.js:51:19)
    at Shop.showMenu (C:\Users\AJAY\AppData\Roaming\npm\node_modules\scope-chains-closures\node_modules\adventure\index.js:267:16)
    at Shop.execute (C:\Users\AJAY\AppData\Roaming\npm\node_modules\scope-chains-closures\node_modules\adventure\index.js:131:14)
    at Object.<anonymous> (C:\Users\AJAY\AppData\Roaming\npm\node_modules\scope-chains-closures\runner.js:26:6)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:118:18)

**Comment by RussEby** [comment]
I had the same issue. I was still able to do the training by using 

`scope-chains-closures next`

The `--help` screen explains quite a bit. Seems that only the menu is broken. The verifying work fine.

**Comment by martinheidegger** [comment]
#27 should fix this issue.
