### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by ahmdshbz** [workshopper/scope-chains-closures#38]
I enter `npm install -g scope-chains-closures` into the terminal and I get the following:
```
path.js:1180
          cwd = process.cwd();
                        ^

Error: ENOENT: no such file or directory, uv_cwd
    at Object.resolve (path.js:1180:25)
    at Function.Module._resolveLookupPaths (module.js:419:17)
    at Function.Module._resolveFilename (module.js:522:22)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at /usr/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/lib/node_modules/npm/bin/npm-cli.js:92:3)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
```

**Comment by ahmdshbz** [comment]
fixed by reentering the directory
