### ISSUE TITLE
Can't execute workshop

### ISSUE THREAD

**Issue by eugeniobaglieri** [workshopper/scope-chains-closures#39]
When I launch the workshop, for every item of the menu, I get this error

```bash
fs.js:140
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:140:9)
    at Object.fs.writeFile (fs.js:1258:14)
    at Shop.save (/usr/local/lib/node_modules/scope-chains-closures/node_modules/adventure/index.js:288:8)
    at Shop.select (/usr/local/lib/node_modules/scope-chains-closures/node_modules/adventure/index.js:246:10)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/scope-chains-closures/node_modules/adventure/index.js:278:14)
    at EventEmitter.emit (events.js:182:13)
    at Menu.<anonymous> (/usr/local/lib/node_modules/scope-chains-closures/node_modules/adventure/lib/menu.js:49:22)
    at Menu.emit (events.js:182:13)
    at Menu.ondata [as _ondata] (/usr/local/lib/node_modules/scope-chains-closures/node_modules/terminal-menu/index.js:215:18)
    at DestroyableTransform._transform (/usr/local/lib/node_modules/scope-chains-closures/node_modules/terminal-menu/index.js:50:18)

**Comment by elpepian** [comment]
Got the same error =/

**Comment by Sceat** [comment]
Use NVM to downgrade node to 8.11.1

**Comment by finnp** [comment]
Try to install `@workshoppers/scope-chains-closures`!
