### ISSUE TITLE
Cannot run the workshopper

### ISSUE THREAD

**Issue by vasileboris** [workshopper/scope-chains-closures#42]
When running this workshopper I see the following error in console 

```
Once complete, execute @workshoppers/scope-chains-closures verify <your-file.js> to verify your
solution.

## Notes

  * [1]: There are also 4 other scopes in the language: Global, `with`, `catch`,
  *      and `eval`. These tend not to be used much, so we will ignore them.
  * 
  * 
  * [2]: This workshop will concentrate only on Lexical Scoping.


events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: shutdown ENOTCONN
    at ReadStream.Socket._final (net.js:366:25)
    at callFinal (_stream_writable.js:612:10)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

and when verifying the solution it says

```
ERROR: No adventure is currently selected. Select an adventure from the menu.
```

I assume that it is because of the above error

**Comment by vasileboris** [comment]
I checked again and the issues are with node 10 (10.5.0 and 10.6.0). It works with node 9 (9.11.2)

**Comment by kaizenkaizen** [comment]
You can work around the issue with

`npm install -g n`
`n  9.11.2`
`sccjs`

**Comment by lolaida** [comment]
I am still having this issue.
